# Generated by Django 3.2.7 on 2021-09-05 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('FName', models.CharField(max_length=50)),
                ('LName', models.CharField(max_length=100)),
                ('Email', models.EmailField(max_length=100)),
                ('Mobile', models.CharField(max_length=20)),
            ],
        ),
    ]
